### PR TITLE
Fix propagation of HTTP error codes

### LINKED ISSUE #7038: [Bug] Not all Client requests properly propagate the http code of the response
### Describe the bug

Found will using the new event `simplepie_after_init` (#7007)  
When processing the event, if the request to the feed fails `$simplePie->status_code` remains at `0` even when the logs show something like:  
```
FreshRSS SimplePie GET 429 http://localhost:4985/custom
[admin] [Sat, 30 Nov 2024 11:59:17 -0500] [warning] --- cURL error 22: The requested URL returned error: 429 [http://localhost:4985/custom]
```  

### To Reproduce

1. Create an extension which registers to the hook `simplepie_after_init` and prints or does something with `$simplePie->status_code`  
2. Update or add a feed which returns an http error (I just ran a local server to force a 429)  
3. See the logs of simplepie receiving the error code, while the extension receives `0`  

### Expected behavior

SimplePie should have the http code the request returned.  

### FreshRSS version

1.25.0-dev

### Environment information

- Database version: SQLite
- PHP version: 8.2.24
- Installation type: Docker image source ( https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/Dockerfile )
- Docker compose https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml  
With these changes to run the checked out code
```
    build:
      # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
      context: ../../
      dockerfile: Docker/Dockerfile
    volumes:
      - ../..:/var/www/freshrss
```
- Web server type: Apache
- Device: 
- OS: Ubuntu 24.04
- Browser: Firefox 133

### Additional context

Seems the issue is a combination of missing parts  
In this section the new exception doesn't have `$file->get_status_code()`
https://github.com/FreshRSS/FreshRSS/blob/a41aadf02add2e326a1cfa320022e5db3600f9d4/lib/simplepie/simplepie/src/HTTP/FileClient.php#L73  

Here `$th->getCode()` should be used instead of a hard-coded `0`  
https://github.com/FreshRSS/FreshRSS/blob/a41aadf02add2e326a1cfa320022e5db3600f9d4/lib/simplepie/simplepie/src/SimplePie.php#L1998-L2002  

Similarly here, in the catch block the code should be taken from the exception  
https://github.com/FreshRSS/FreshRSS/blob/a41aadf02add2e326a1cfa320022e5db3600f9d4/lib/simplepie/simplepie/src/SimplePie.php#L2092-L2101

I'm still looking into how actually the property `$status_code` of `File` is populated and where is being used to know if there are more cases which might not fill in the value of the response.

### PR DESCRIPTION
**Pull request by pe1uca**
Fixes FreshRSS/FreshRSS#7038

Cherry-picked from simplepie/simplepie#905

### CODE REVIEW

File: src/HTTP/FileClient.php [hunk 1]
```diff
@@ -70,7 +70,7 @@ public function request(string $method, string $url, array $headers = []): Respo
         }
 
         if (!$file->success) {
-            throw new HttpException($file->error);
+            throw new HttpException($file->error, $file->get_status_code());
```
Comment (Alkarex) [inline src/HTTP/FileClient.php]:
```suggestion
            throw new HttpException($file->error, $file->get_status_code());	// FreshRSS https://github.com/simplepie/simplepie/pull/905
```

To be removed when changed upstream. Help me keeping track of changes

File: src/SimplePie.php [hunk 2]
```diff
@@ -1999,7 +1999,7 @@ protected function fetch_data(&$cache)
                             $this->status_code = $file->get_status_code();
                         } catch (HttpException $th) {
                             $this->check_modified = false;
-                            $this->status_code = 0;
+                            $this->status_code = $th->getCode();
```
Comment (Alkarex) [inline src/SimplePie.php]:
```suggestion
                            $this->status_code = $th->getCode();	// FreshRSS https://github.com/simplepie/simplepie/pull/905
```

File: src/SimplePie.php [hunk 3]
```diff
@@ -2093,6 +2093,7 @@ protected function fetch_data(&$cache)
                 } catch (HttpException $th) {
                     // If the file connection has an error, set SimplePie::error to that and quit
                     $this->error = $th->getMessage();
+                    $this->status_code = $th->getCode();
```
Comment (Alkarex) [inline src/SimplePie.php]:
```suggestion
                    $this->status_code = $th->getCode();	// FreshRSS https://github.com/simplepie/simplepie/pull/905
```

**Review by Alkarex — APPROVED** [review]

**Comment by Alkarex** [comment]
Additional tests welcome, following: 
* https://github.com/FreshRSS/simplepie/pull/47
* https://github.com/FreshRSS/FreshRSS/pull/7775
